-   id: djlint-format-hook
    name: djLint Format
    description: Formats all html templates with djLint
    entry: djlint --reformat --format-css --format-js
    types_or: [html]
    language: system
